/**
 * DISCOVER PALAWAN — Destinations Data
 * All tourist destinations stored in a JS array
 */

const DESTINATIONS = [
    {
        id: 1,
        name: "Big Lagoon",
        city: "El Nido",
        category: "Island",
        image: "images/el_nido.jpg",
        shortDesc: "A breathtaking emerald lagoon enclosed by towering limestone cliffs, accessible only by kayak or boat.",
        fullDesc: "The Big Lagoon in El Nido is one of Palawan's most iconic natural wonders. Enclosed by dramatic limestone karst formations rising straight from the sea, the lagoon's calm, crystal-clear emerald waters reflect the surrounding cliffs in a scene that seems almost unreal. The lagoon is part of the Bacuit Archipelago and sits within the El Nido Marine Reserve. Visitors enter through a narrow channel, kayaking or swimming through the passage to reveal the vast open lagoon beyond. The shallow waters reveal a colorful world of corals and marine life below.",
        location: "El Nido, Palawan",
        activities: ["Kayaking", "Swimming", "Snorkeling", "Photography", "Island hopping (Tour A)"],
        bestTime: "November to May (dry season). Avoid monsoon season (June–October).",
        entranceFee: "₱200 environmental fee (El Nido Eco-tourism fee)",
        openingHours: "7:00 AM – 5:00 PM daily",
        travelTips: "Book a Tour A island hopping package from El Nido town. Bring waterproof bags for electronics. Sunscreen is essential. Arrive early to beat the crowds.",
        tags: ["lagoon", "el nido", "island", "kayaking", "snorkeling"]
    },
    {
        id: 2,
        name: "Kayangan Lake",
        city: "Coron",
        category: "Mountain",
        image: "images/coron.avif",
        shortDesc: "Declared the cleanest lake in Asia, Kayangan is a stunning mountain lake framed by karst cliffs in Coron.",
        fullDesc: "Kayangan Lake in Coron is widely regarded as one of the most beautiful lakes in the Philippines and was once declared the cleanest lake in Asia. Reached via a short but steep hike over a limestone ridge (rewarded with a spectacular viewpoint overlooking Coron Bay), the lake itself is a surreal mix of freshwater and saltwater. Beneath the surface lies an otherworldly landscape of submerged rock formations and crystal-clear waters with visibility of up to 10 meters. The lake is surrounded by towering karst limestone walls draped in tropical vegetation.",
        location: "Coron Island, Coron, Palawan",
        activities: ["Swimming", "Snorkeling", "Hiking", "Cliff jumping", "Photography"],
        bestTime: "October to May. Best avoided during heavy rain season.",
        entranceFee: "₱200 Coron Island Nature Fee + ₱100 Kayangan Lake Fee",
        openingHours: "6:00 AM – 5:00 PM daily",
        travelTips: "Hire a local bangka boat from Coron town pier. The hike to the viewpoint takes about 15 minutes. Bring water shoes as the rocks can be slippery. No single-use plastics allowed.",
        tags: ["lake", "coron", "snorkeling", "mountain", "hike"]
    },
    {
        id: 3,
        name: "Puerto Princesa Underground River",
        city: "Puerto Princesa",
        category: "Adventure",
        image: "images/puerto_princesa.webp",
        shortDesc: "A UNESCO World Heritage Site and New 7 Wonder of Nature — the world's longest navigable underground river.",
        fullDesc: "The Puerto Princesa Subterranean River National Park is one of the most extraordinary natural wonders on Earth. Listed as a UNESCO World Heritage Site and one of the New 7 Wonders of Nature, the underground river stretches approximately 8.2 kilometers through a stunning cave system before emptying directly into the South China Sea. Visitors board small paddle boats to navigate the cavern, passing through enormous chambers filled with dramatic stalactite and stalagmite formations. The park also contains one of Asia's most important rainforest ecosystems, home to hundreds of bird and reptile species.",
        location: "Puerto Princesa, Palawan",
        activities: ["Underground river tour", "Bird watching", "Forest trekking", "Beach picnic", "Photography"],
        bestTime: "December to May. The cave may close during heavy weather.",
        entranceFee: "₱150 entrance fee + ₱200 paddle boat fee",
        openingHours: "8:00 AM – 4:00 PM (last tour at 3:30 PM)",
        travelTips: "Advance booking is mandatory and highly recommended. Book through the City Tourism Office or accredited tour operators. The site is 80km from Puerto Princesa city — budget 2 hours travel time each way. Bring insect repellent.",
        tags: ["underground river", "puerto princesa", "UNESCO", "cave", "world wonder"]
    },
    {
        id: 4,
        name: "Fort Santa Isabel",
        city: "Taytay",
        category: "Historical Site",
        image: "images/taytay.webp",
        shortDesc: "A 17th-century Spanish colonial fort overlooking Taytay Bay — one of Palawan's most significant historical landmarks.",
        fullDesc: "Fort Santa Isabel (also known as Fort Fuerza de Santa Isabel) was built by the Spanish colonial government in 1667, originally to defend against Dutch and Moro raiders. The fort occupies a strategic hilltop position overlooking Taytay Bay on the northeastern coast of Palawan. Today, the well-preserved ruins consist of coral stone walls, bastions, and the remains of a church built within the fort's enclosure. The site offers panoramic views of the blue-green bay dotted with fishing boats and tropical islands. Taytay itself served as Palawan's capital before Puerto Princesa, giving the fort significant historical importance.",
        location: "Taytay, Palawan",
        activities: ["Heritage tour", "Photography", "Sunset viewing", "Historical exploration", "Swimming in bay"],
        bestTime: "Year-round, though dry season (November–May) is ideal. Sunsets are spectacular.",
        entranceFee: "₱30–50 (small conservation fee)",
        openingHours: "8:00 AM – 5:00 PM daily",
        travelTips: "Combine your visit with island hopping in Taytay Bay. The fort is a 10-minute tricycle ride from Taytay town. Wear comfortable shoes for the uneven stone surfaces. Visit at sunset for dramatic photography.",
        tags: ["fort", "taytay", "historical", "spanish", "colonial", "heritage"]
    },
    {
        id: 5,
        name: "Long Beach",
        city: "San Vicente",
        category: "Beach",
        image: "images/san_vicente.jpg",
        shortDesc: "The longest beach in the Philippines at 14.7 km — an unspoiled stretch of white sand and turquoise sea.",
        fullDesc: "Long Beach in San Vicente, Palawan is the longest beach in the Philippines, stretching an unbroken 14.7 kilometers of powdery white sand along the South China Sea coast. Unlike more developed beach destinations, Long Beach remains largely pristine and uncrowded, offering an authentic slice of tropical paradise. The beach is backed by coconut palms and rolling hills, with the azure waters grading from shallow turquoise to deep sapphire. Development here is carefully planned, with an eco-tourism master plan aimed at preserving the natural environment. Sunsets here are legendary among travellers.",
        location: "San Vicente, Palawan",
        activities: ["Swimming", "Beach walking", "Sunset watching", "Surfing (seasonal)", "Camping", "Kiteboarding"],
        bestTime: "November to May. Some surf from October–November.",
        entranceFee: "Free (some resort sections may charge for facilities)",
        openingHours: "Open 24 hours",
        travelTips: "San Vicente is accessible by van or bus from Puerto Princesa (4–5 hours). Choose your accommodation on the beach itself to maximize your experience. The beach is long enough that you'll rarely feel crowded. Bring sun protection.",
        tags: ["long beach", "san vicente", "white sand", "beach", "Philippines longest beach"]
    },
    {
        id: 6,
        name: "El Nido Town & Bacuit Bay",
        city: "El Nido",
        category: "Island",
        image: "images/el_nido.jpg",
        shortDesc: "World-famous for its dramatic limestone karst islands, hidden lagoons, and some of the clearest waters on Earth.",
        fullDesc: "El Nido is the crown jewel of Palawan, a stunning archipelago of 45 islands and islets set in the Bacuit Bay. The landscape is dominated by ancient limestone karst formations rising dramatically from turquoise waters, creating secret lagoons, pristine beaches, snorkeling spots, and sea caves. The town of El Nido serves as the jumping-off point for four official island-hopping tours (A, B, C, and D), each visiting different clusters of islands. Marine life is abundant — rays, sea turtles, reef sharks, and extraordinary corals. El Nido is also the gateway to the Palawan Biosphere Reserve.",
        location: "El Nido, Palawan",
        activities: ["Island hopping", "Snorkeling", "Diving", "Kayaking", "Cliff jumping", "Beach camping"],
        bestTime: "November to April is best. Expect rain and occasional rough seas from June to October.",
        entranceFee: "₱200 Environmental Fee per person (valid for 10 days)",
        openingHours: "Tours depart 8:00 AM – 5:00 PM",
        travelTips: "Book tour boats at least one day ahead during peak season. Tours A and C are the most popular — try Tour B and D for fewer crowds. Bring reef-safe sunscreen only. Stay at least 3–5 nights to experience multiple tours.",
        tags: ["el nido", "island", "lagoon", "bacuit", "island hopping"]
    },
    {
        id: 7,
        name: "Coron Town & Reefs",
        city: "Coron",
        category: "Adventure",
        image: "images/coron.avif",
        shortDesc: "World-class wreck diving, stunning lakes, and coral reefs in one of Asia's most beautiful diving destinations.",
        fullDesc: "Coron in northern Palawan is a world-renowned destination famed for its WWII Japanese shipwrecks, pristine lakes, and spectacular coral reefs. The town sits on Busuanga Island, with boat trips taking visitors to the neighboring Coron Island. The Coron Bay contains over a dozen Japanese warships sunk in a 1944 US airstrike, now resting at depths of 10–45 meters draped in colorful corals — making it one of the world's finest wreck diving destinations. Above water, crystal-clear lakes (Kayangan, Twin Lagoon, Barracuda Lake) and white sand beaches complete an extraordinary experience.",
        location: "Coron, Palawan",
        activities: ["Wreck diving", "Snorkeling", "Lake swimming", "Island hopping", "Kayaking", "Hot spring bathing"],
        bestTime: "October to May. Diving visibility is best December to May.",
        entranceFee: "₱200 Coron Island Nature Fee + individual site fees",
        openingHours: "Tours: 7:30 AM – 5:00 PM",
        travelTips: "Coron has direct flights from Manila. Book dive packages with reputable operators. Non-divers will still find plenty to do. Taste the local seafood at the market — it's exceptional and affordable.",
        tags: ["coron", "diving", "wreck", "lake", "snorkeling"]
    },
    {
        id: 8,
        name: "Port Barton Beach",
        city: "San Vicente",
        category: "Beach",
        image: "images/port_barton.jpg",
        shortDesc: "A laid-back beach village with pristine coral reefs, waterfalls, and an authentic island atmosphere.",
        fullDesc: "Port Barton is a small, relaxed beach village on Palawan's west coast, popular among travelers seeking a quieter alternative to El Nido or Coron. The village sits on a beautiful bay sheltered by mangroves and dotted with coral-rich islands. Island-hopping tours visit secluded beaches, crystal waterfalls tumbling into the sea, and vibrant reef ecosystems. The Pawikan Marine Wildlife Sanctuary nearby protects sea turtles. The local community has committed to eco-tourism, keeping the atmosphere unhurried, authentic, and in harmony with nature.",
        location: "Port Barton, San Vicente, Palawan",
        activities: ["Island hopping", "Snorkeling", "Swimming", "Waterfall visits", "Sunset watching", "Beach relaxation"],
        bestTime: "November to May.",
        entranceFee: "₱100–200 depending on activities",
        openingHours: "Open year-round; tours 7:00 AM – 4:30 PM",
        travelTips: "Port Barton is accessible by van from Puerto Princesa (3–4 hours). It has limited ATM access — bring enough cash. The relaxed pace is intentional; embrace it. Accommodation ranges from basic cottages to comfortable beach bungalows.",
        tags: ["port barton", "beach", "snorkeling", "laid back", "eco tourism"]
    },
    {
        id: 9,
        name: "Tubbataha Reef",
        city: "Puerto Princesa",
        category: "Adventure",
        image: "images/diving.webp",
        shortDesc: "A UNESCO World Heritage Site and one of the world's premier diving destinations — a pristine oceanic reef teeming with marine life.",
        fullDesc: "Tubbataha Reef Natural Park is located in the Sulu Sea, about 180 km southeast of Puerto Princesa. A UNESCO World Heritage Site since 1993, Tubbataha consists of two remote coral atolls and the Jessie Beazley Reef. This pristine ecosystem is home to over 600 fish species, 360 coral species, 11 shark species, sea turtles, manta rays, and millions of seabirds. Only accessible by liveaboard dive boats, Tubbataha represents the Philippines' finest marine conservation success story. The diving here is exceptional — walls dropping hundreds of meters, drift diving, and encounters with hammerhead sharks.",
        location: "Sulu Sea, Puerto Princesa, Palawan",
        activities: ["Scuba diving", "Snorkeling", "Photography", "Marine biology observation"],
        bestTime: "March to June only (the park is closed the rest of the year).",
        entranceFee: "₱4,000–6,000+ (park fees per person); liveaboard packages ₱60,000–150,000+",
        openingHours: "March to June only",
        travelTips: "Tubbataha is exclusively for experienced divers, accessible only via liveaboard dive boats departing from Puerto Princesa. Book 6–12 months in advance during open season. Contact TPAMB (Tubbataha Protected Area Management Board) for accredited operators.",
        tags: ["tubbataha", "diving", "reef", "UNESCO", "marine", "liveaboard"]
    },
    {
        id: 10,
        name: "Twin Lagoon",
        city: "Coron",
        category: "Island",
        image: "images/coron.avif",
        shortDesc: "Two connected lagoons separated by a low limestone cliff — one saltwater, one a thermocline mix of warm and cold water.",
        fullDesc: "Twin Lagoon in Coron is one of the most unique natural phenomena in Palawan. Two lagoons are separated by a limestone cliff with a small opening that can only be passed by swimming under the rock passage (or over it at low tide). The outer lagoon features saltwater with crystal-clear visibility. The inner lagoon has a remarkable thermocline — two layers of water at different temperatures, one warm freshwater above and cool saltwater below. The surrounding limestone walls draped with vegetation create a dramatic, intimate atmosphere that makes Twin Lagoon one of Coron's most photographed sites.",
        location: "Coron Island, Coron, Palawan",
        activities: ["Swimming", "Snorkeling", "Photography", "Kayaking"],
        bestTime: "October to May. Morning visits offer the best light.",
        entranceFee: "₱200 Coron Island Nature Fee (covers multiple sites)",
        openingHours: "8:00 AM – 4:00 PM",
        travelTips: "Include Twin Lagoon in your Coron island-hopping tour. The passage between lagoons requires swimming — life jackets are available. Bring an underwater camera. The thermocline effect is most noticeable by swimming down through the water column.",
        tags: ["twin lagoon", "coron", "island", "snorkeling", "swimming"]
    },
    {
        id: 11,
        name: "Nacpan Beach",
        city: "El Nido",
        category: "Beach",
        image: "images/el_nido.jpg",
        shortDesc: "A stunning 4-kilometer twin beach of golden sand, often ranked among Asia's most beautiful beaches.",
        fullDesc: "Nacpan Beach is a 4-kilometer stretch of golden sand in El Nido, connected at its northern end to the smaller Calitang Beach — together forming what locals call the Twin Beaches. Less crowded than the main El Nido town area beaches, Nacpan has retained a natural, unhurried character with good waves, swimmable waters, and a forested backdrop. Local vendors offer fresh coconuts and simple meals along the beach. The drive to Nacpan itself is an adventure through rolling hills and small villages. Nacpan consistently ranks among Southeast Asia's most beautiful beaches.",
        location: "El Nido, Palawan",
        activities: ["Swimming", "Beach volleyball", "Surfing (seasonal)", "Sunset watching", "Hammock relaxing"],
        bestTime: "November to May.",
        entranceFee: "Free",
        openingHours: "Open 24 hours",
        travelTips: "Hire a motorbike or join a tour group from El Nido town (30–45 min ride). The road is partly unpaved — a 4x4 or motorbike handles it better. Bring cash for food and drinks as no ATMs are nearby. Combine with a visit to nearby Calitang Beach.",
        tags: ["nacpan", "el nido", "beach", "twin beach", "golden sand"]
    },
    {
        id: 12,
        name: "Honda Bay",
        city: "Puerto Princesa",
        category: "Island",
        image: "images/puerto_princesa.webp",
        shortDesc: "A sheltered bay near Puerto Princesa city with white sand islands, mangrove ecosystems, and vivid coral gardens.",
        fullDesc: "Honda Bay is a shallow, protected bay located just 12 kilometers north of Puerto Princesa city, making it one of the most accessible island-hopping destinations in Palawan. The bay contains numerous small islands — Starfish Island, Luli Island (which disappears at high tide), Pandan Island, and Snake Island among them — each with its own white sand beach and coral reef. The waters are calm and clear, perfect for snorkeling, swimming, and picnicking. Honda Bay is ideal for day trips from the city, offering a taste of Palawan island life without extensive travel.",
        location: "Puerto Princesa, Palawan",
        activities: ["Island hopping", "Snorkeling", "Swimming", "Starfish spotting", "Picnicking"],
        bestTime: "November to May. Avoid during monsoon season.",
        entranceFee: "₱150 entrance fee per island visited",
        openingHours: "7:00 AM – 4:00 PM",
        travelTips: "Arrange tours at the Santa Lourdes Wharf in Puerto Princesa. Packages include 3–5 islands. Bring reef-safe sunscreen and snorkeling gear (rentals available). Combine with a visit to the Underground River for a full Palawan city experience.",
        tags: ["honda bay", "puerto princesa", "island hopping", "snorkeling", "day trip"]
    }
];

// Make destinations available globally
window.DESTINATIONS = DESTINATIONS;
